######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 3 10:33:57 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += controler.h CProgresDialog.h cthread.h ui_progres_dialog.h window.h
SOURCES += controler.cpp CProgresDialog.cpp cthread.cpp main.cpp window.cpp
